### ISSUE TITLE
what is difference between listed pretrained models

### ISSUE THREAD

**Issue by wengbrian** [mzweilin/EvadeML-Zoo#2]
Hi, I want to ask that what is difference between "PGDbase" and "PGDtrained" model listed in [here](https://github.com/mzweilin/EvadeML-Zoo/blob/master/models/README.md) for MNIST dataset. Also, there seems to exist two Cleverhans MNIST for mnist which I found in your code [here](https://github.com/mzweilin/EvadeML-Zoo/blob/master/datasets/mnist.py), what is difference between these two model? Final, can you provide training detail that how is these models pretrained? for example, how many epoch used to train each of these model or some setting?

**Comment by mzweilin** [comment]
The "cleverhans" means the model architecture is from the MNIST example in Cleverhans. We have two models with the same prefix, one is adversarially trained while the other is not, so that you can compare the robustness property. 

Sorry, I didn't document the training protocol for the models.

Best,
-Weilin
